---
# tasks file for nginx-hosting
- name: installing nginx
  dnf:
    name: "{{pack}}"
    state: present
- name: enabling nginx
  service:
    name: "{{pack}}"
    enabled: yes
    state: started
- name: copy files
  copy:
    src: web
    dest: /var/www/html
  notify: restart nginx
- name: templating
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/web.conf
  notify: restart nginx
- name: add http,https
  firewalld:
    service: "{{item}}"
    state: enabled
    permanent: true
  notify: firewall
  loop:
    - http
    - https
- name: selinux
  selinux:
    policy: targeted
    state: permissive
